
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team02-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: team02-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOB00C0g","is_bot":false,"login":"spark686","name":""},"headRefName":"sp-Article-controller","number":65,"title":"Created article controller including put, get, and delete","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-8/pull/65"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-put","number":61,"title":"hs- Add PUT (edit) endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-8/pull/61"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-delete","number":60,"title":"hs- Add DELETE endpoint for a specific record in HelpRequest table","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-8/pull/60"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-show","number":55,"title":"Add Get for a single HelpRequest","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-8/pull/55"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-get-post","number":54,"title":"Created HelpRequestController, add GET and POST","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-8/pull/54"},{"author":{"id":"U_kgDOBdCSgA","is_bot":false,"login":"Hannahshakouri01","name":"Hannah Shakouri"},"headRefName":"hs-HelpRequest-create-db","number":47,"title":"hs- Add HelpRequest db Table ","url":"https://github.com/ucsb-cs156-s24/team02-s24-5pm-8/pull/47"}]
